import type { FAQ } from './regions';

export interface CityConfig {
  slug: string;
  urlSlug: string; // e.g. 'london-onlyfans'
  label: string;
  terms: string[];
  parentRegion: string; // region slug
  h1: string;
  metaTitle: string;
  metaDesc: string;
  intro: string;
  faqs: FAQ[];
  relatedCities: string[]; // sibling city slugs
  relatedRegions?: string[]; // optional related region slugs
}

export const cities: CityConfig[] = [
  {
    slug: 'london',
    urlSlug: 'london-onlyfans',
    label: 'London',
    terms: ['london', 'east london', 'west london', 'north london', 'south london', 'hackney', 'shoreditch', 'camden', 'brixton', 'peckham', 'clapham', 'islington', 'soho'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in London',
    metaTitle: 'Best London OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: 'Find the hottest OnlyFans creators from London. Browse East London, Camden, Brixton and beyond. Free and premium content updated daily.',
    intro: "London is undisputedly Britain's OnlyFans capital. Home to over 9 million people representing virtually every culture on earth, the city's sheer diversity produces a creator ecosystem that is unmatched anywhere in the UK. From the edgy creative energy of Hackney and Shoreditch to the bohemian vibes of Camden and the multicultural soul of Brixton and Peckham, London's neighbourhoods each produce distinct creator aesthetics. The city's enormous population of students, young professionals and artists creates a constantly refreshing pool of new talent. London creators invest heavily in production quality, benefiting from the city's professional photography studios, high-end fashion culture and international media industry. Updated daily with new profiles across every niche and price point.",
    faqs: [
      { q: 'How many OnlyFans creators are in London?', a: 'London has more OnlyFans creators than any other UK city by a significant margin. Our directory indexes thousands of London-based profiles across every category, from free accounts to premium verified creators.' },
      { q: 'Which areas of London have the most OnlyFans creators?', a: 'East London (Hackney, Shoreditch, Bow) and South London (Brixton, Peckham, Clapham) have the highest creator density. Camden, Islington and North London also contribute many alt and lifestyle creators.' },
      { q: 'Can I find verified London OnlyFans creators?', a: "Yes — toggle the Verified filter to show only London creators who have completed OnlyFans' identity verification process." },
      { q: 'Do London creators offer bundle deals?', a: "Many do. London's competitive creator market means subscription discounts and bundle deals are common. Check individual profile cards for bundle pricing information." },
    ],
    relatedCities: ['birmingham', 'manchester', 'brighton'],
  },
  {
    slug: 'manchester',
    urlSlug: 'manchester-onlyfans',
    label: 'Manchester',
    terms: ['manchester', 'salford', 'trafford', 'northern quarter', 'didsbury', 'chorlton', 'fallowfield'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Manchester',
    metaTitle: 'Best Manchester OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Discover top OnlyFans creators from Manchester. Browse the Northern Quarter, Didsbury and beyond. Free and premium profiles updated daily.",
    intro: "Manchester's creative confidence — built on music, fashion and a fierce northern identity — translates directly into one of the UK's most compelling OnlyFans creator communities. The city that gave the world the Hacienda, Oasis and a global football obsession now produces creators who carry that same spirit of bold self-expression into the digital economy. The Northern Quarter's indie energy, Didsbury's affluent lifestyle aesthetic and Fallowfield's student population create distinct creator clusters within a single city. Manchester's large LGBTQ+ community, centred on the famous Gay Village around Canal Street, contributes exceptional diversity and some of the UK's most boundary-pushing creator content. The city's three major universities ensure a constant influx of new talent.",
    faqs: [
      { q: "Is Manchester a major city for OnlyFans creators?", a: "Absolutely — Manchester is England's second city for OnlyFans creator volume after London. The city's creative culture, student population and strong LGBTQ+ community produce exceptional variety across every content niche." },
      { q: 'What neighbourhoods have the most Manchester OnlyFans creators?', a: "Fallowfield and Withington (student areas), the Northern Quarter (creative/alt), Didsbury (lifestyle) and the Gay Village area are the highest-density creator neighbourhoods." },
      { q: 'Are there free Manchester OnlyFans accounts?', a: "Yes — many Manchester creators use free subscriptions to build their following. Filter by 'Free' in the pricing section to see all free Manchester profiles instantly." },
      { q: 'What content styles are Manchester creators known for?', a: "Manchester has exceptional strength in alt/goth, LGBT+ content, amateur and authentic content. The city's anti-pretension culture produces creators who pride themselves on genuine fan connection." },
    ],
    relatedCities: ['liverpool', 'leeds', 'sheffield'],
  },
  {
    slug: 'birmingham',
    urlSlug: 'birmingham-onlyfans',
    label: 'Birmingham',
    terms: ['birmingham', 'brum', 'brummie', 'digbeth', 'jewellery quarter', 'moseley', 'erdington'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Birmingham',
    metaTitle: 'Best Birmingham OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: 'Find Birmingham OnlyFans creators from Digbeth, Moseley and across the Midlands. Browse free and premium profiles updated daily.',
    intro: "Birmingham — the UK's second-largest city and its most diverse — brings an extraordinary multicultural richness to its OnlyFans creator community. Home to one of Europe's youngest and most diverse populations, Birmingham's creators reflect the full spectrum of British multicultural identity. Digbeth's creative quarter has become a magnet for artistic and alt creators, while Moseley's bohemian character attracts musicians and lifestyle creators. The city's five universities provide a constant influx of student creators who bring fresh energy and new perspectives. Birmingham creators are known for being authentic, entrepreneurial and value-conscious.",
    faqs: [
      { q: 'How diverse is the Birmingham OnlyFans creator community?', a: "Birmingham is one of the UK's most diverse cities, and this is strongly reflected in its creator community. You'll find exceptional representation from South Asian, Black British and mixed-heritage creators." },
      { q: 'Are there free Birmingham OnlyFans accounts?', a: "Yes — multiple Birmingham creators offer free subscription accounts. Use the Free pricing filter to find them instantly." },
      { q: 'What content niches are Birmingham creators strong in?', a: "Birmingham has exceptional strength in multicultural content, alt/creative, amateur and lifestyle niches. Digbeth's creative community produces notably artistic content." },
      { q: 'Can I find verified creators from Birmingham?', a: "Yes — toggle the Verified filter to find ID-confirmed creators from Birmingham and the wider West Midlands area." },
    ],
    relatedCities: ['manchester', 'nottingham', 'leicester'],
  },
  {
    slug: 'glasgow',
    urlSlug: 'glasgow-onlyfans',
    label: 'Glasgow',
    terms: ['glasgow', 'west end glasgow', 'merchant city', 'govanhill', 'southside glasgow'],
    parentRegion: 'scotland',
    h1: 'Best OnlyFans Creators in Glasgow',
    metaTitle: 'Best Glasgow OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: 'Find the hottest Glasgow OnlyFans creators from the West End, Merchant City and beyond. Free and premium Scottish profiles.',
    intro: "Glasgow is Scotland's largest city and its most electrifying, producing an OnlyFans creator community that perfectly embodies the city's famously bold, direct and warmly funny character. The city's extraordinary arts and music heritage — Glasgow School of Art and the legendary live music scene — has cultivated a creative class that approaches content creation with genuine artistic ambition and zero pretension. Glasgow's large LGBTQ+ community contributes significant diversity and some of Scotland's most celebrated creator content. Glasgow creators are known throughout the UK fan community for their exceptional fan engagement — the city's famous warmth and directness translate into creator-fan relationships that subscribers describe as uniquely genuine.",
    faqs: [
      { q: "What is Glasgow's reputation in the UK OnlyFans community?", a: "Glasgow creators are particularly celebrated for their warmth, authenticity and exceptional fan engagement. The city's cultural confidence and anti-pretension character translates into creator-fan relationships that subscribers consistently rate highly." },
      { q: 'Are there many alt or goth creators in Glasgow?', a: "Yes — Glasgow's strong arts and music scene has produced a thriving alt, goth and alternative creator community." },
      { q: 'Can I find free Glasgow OnlyFans accounts?', a: "Multiple Glasgow creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: 'Do Glasgow creators post regularly?', a: "Glasgow's full-time creator community is highly active and posting frequency is generally high." },
    ],
    relatedCities: ['edinburgh', 'aberdeen'],
  },
  {
    slug: 'liverpool',
    urlSlug: 'liverpool-onlyfans',
    label: 'Liverpool',
    terms: ['liverpool', 'merseyside', 'scouser', 'bold street', 'ropewalks'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Liverpool',
    metaTitle: 'Best Liverpool OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Liverpool's best OnlyFans creators from Bold Street, Ropewalks and across Merseyside. Updated daily.",
    intro: "Liverpool's OnlyFans community carries the same infectious energy that has made the city famous worldwide for music, football and unstoppable cultural self-confidence. Bold Street and the Baltic Triangle's arts community have produced genuinely artistic content creators whose work sits between social media and gallery-quality production. Liverpool creators are known throughout the UK fan community for exceptional warmth and the kind of direct, sarcastic Scouse humour that international fans find irresistible. The city's three universities contribute a strong student creator demographic.",
    faqs: [
      { q: "What is Liverpool's OnlyFans scene like?", a: "Liverpool has a vibrant and rapidly growing creator community. The city's cultural confidence, student population and thriving arts scene have created excellent conditions for content creation across all niches." },
      { q: 'Are there free Liverpool OnlyFans accounts?', a: "Yes — multiple Liverpool creators offer free subscriptions. Use the Free pricing filter to find free accounts from Liverpool and the wider Merseyside area." },
      { q: "What makes Liverpool creators distinctive?", a: "Liverpool creators are celebrated for their humour, warmth and exceptional fan engagement. The city's famous Scouse wit creates creator personalities that fans describe as genuinely likeable." },
      { q: 'Can I find verified Liverpool OnlyFans creators?', a: "Yes — toggle the Verified filter to find identity-confirmed creators from Liverpool and Merseyside." },
    ],
    relatedCities: ['manchester', 'sheffield', 'leeds'],
  },
  {
    slug: 'edinburgh',
    urlSlug: 'edinburgh-onlyfans',
    label: 'Edinburgh',
    terms: ['edinburgh', 'leith', 'new town edinburgh', 'old town edinburgh', 'morningside'],
    parentRegion: 'scotland',
    h1: 'Best OnlyFans Creators in Edinburgh',
    metaTitle: 'Best Edinburgh OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Discover Edinburgh's top OnlyFans creators from Leith, the New Town and beyond. Browse free and premium Scottish profiles.",
    intro: "Edinburgh is Britain's most visually spectacular capital, and its OnlyFans creator community reflects the city's extraordinary character — intellectually sophisticated, internationally connected and possessed of a proud artistic identity. The Edinburgh Festival Fringe — the largest arts festival in the world — directly energises the local creator economy. Leith's creative renaissance has attracted artists and lifestyle creators who use the neighbourhood's unique industrial-meets-artisan aesthetic to produce distinctive content. Edinburgh's large international student population adds significant diversity to the local creator community.",
    faqs: [
      { q: 'Is Edinburgh a significant city for UK OnlyFans creators?', a: "Yes — Edinburgh is Scotland's second city for creator volume after Glasgow, and has a particularly strong reputation for quality and international appeal." },
      { q: 'Do Edinburgh creators use the city as a backdrop?', a: "Extensively — Edinburgh's castle, Old Town closes, Georgian streets and Leith waterfront are all popular content locations." },
      { q: 'Are there free Edinburgh OnlyFans accounts?', a: "Several Edinburgh creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: "What content styles are Edinburgh creators known for?", a: "Edinburgh has notable strength in artistic, literary-influenced and lifestyle content. The Fringe festival influence produces strong cosplay and performance-art adjacent content." },
    ],
    relatedCities: ['glasgow', 'aberdeen'],
  },
  {
    slug: 'bristol',
    urlSlug: 'bristol-onlyfans',
    label: 'Bristol',
    terms: ['bristol', 'clifton', 'stokes croft', 'bedminster', 'southville', 'harbourside bristol'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Bristol',
    metaTitle: 'Best Bristol OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Bristol's best OnlyFans creators from Stokes Croft, Clifton and the Harbourside. Updated daily with free and premium profiles.",
    intro: "Bristol has one of the UK's most fiercely independent creative cultures — the city that gave the world Banksy, Massive Attack and a tradition of radical self-expression now applies that same creative ambition to OnlyFans content creation. Stokes Croft is home to a concentration of alt, artistic and boundary-pushing creators whose work genuinely stands out in a saturated market. Clifton's Victorian elegance provides a contrasting lifestyle creator cluster. Bristol's deeply embedded culture of authenticity produces creators who build genuinely community-focused subscriber relationships.",
    faqs: [
      { q: "What makes Bristol's OnlyFans content distinctive?", a: "Bristol's counterculture roots produce creator content with genuine artistic ambition and independence. The Stokes Croft and Clifton communities create content that bridges street art aesthetics and alternative culture in ways unique to Bristol." },
      { q: 'Are there alt or goth creators in Bristol?', a: "Bristol has one of the strongest alt/goth creator communities in England outside London. Stokes Croft's counterculture concentration produces exceptional alternative content." },
      { q: 'Can I find free Bristol OnlyFans accounts?', a: "Yes — many Bristol creators use free subscriptions, reflecting the city's culture of accessibility. Use the Free pricing filter to find them." },
      { q: 'What areas of Bristol have the most creators?', a: "Stokes Croft, Clifton, Bedminster and Southville have the highest creator density." },
    ],
    relatedCities: ['london', 'cardiff', 'birmingham'],
  },
  {
    slug: 'leeds',
    urlSlug: 'leeds-onlyfans',
    label: 'Leeds',
    terms: ['leeds', 'headingley', 'hyde park leeds', 'meanwood', 'chapeltown leeds'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Leeds',
    metaTitle: 'Best Leeds OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Leeds' best OnlyFans creators. Browse Headingley, Hyde Park and the city centre. Free and premium Yorkshire profiles updated daily.",
    intro: "Leeds has quietly established itself as one of England's most exciting OnlyFans creator cities. The UK's fourth-largest city is home to four major universities, creating a massive student population that provides both new creator talent and an engaged local subscriber base. The Headingley area is a particular hub for emerging creators, while Hyde Park's bohemian and multicultural character contributes excellent diversity. Leeds creators are known for being hard-working, value-for-money focused and genuinely committed to their craft.",
    faqs: [
      { q: "Is Leeds a growing city for OnlyFans creators?", a: "Absolutely — Leeds is one of England's fastest-growing creator cities. The combination of four major universities, a young population and strong entrepreneurial culture has produced a rapidly expanding creator community." },
      { q: 'What areas of Leeds have the most creators?', a: "Headingley and Hyde Park (student areas), the city centre creative quarter and Chapeltown all have significant creator populations." },
      { q: 'Are there free Leeds OnlyFans accounts?', a: "Yes — many Leeds creators offer free subscriptions, particularly in the student creator segment. Use the Free pricing filter to find them." },
      { q: 'What content types are Leeds creators known for?', a: "Leeds has strong representation in fitness, lifestyle, amateur and authentic working-class content. The city's student population produces particularly good coverage of the student/college niche." },
    ],
    relatedCities: ['manchester', 'sheffield', 'liverpool'],
  },
  {
    slug: 'sheffield',
    urlSlug: 'sheffield-onlyfans',
    label: 'Sheffield',
    terms: ['sheffield', 'ecclesall road', 'kelham island', 'broomhill sheffield'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Sheffield',
    metaTitle: 'Best Sheffield OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Discover Sheffield's OnlyFans creators from Kelham Island, Ecclesall Road and across the city. Browse free and premium Steel City profiles.",
    intro: "Sheffield — the Steel City — has reinvented its economy from industrial powerhouse to creative and digital hub, and its OnlyFans creator community carries the same authentic, no-nonsense character that has always defined the city. Kelham Island's transformation from industrial wasteland to craft brewery and creative district has produced a cluster of artistic and alt creators. Sheffield's two major universities maintain a constant influx of new student creators. Sheffield creators are celebrated for being genuine, reliable and producing consistently high-quality content.",
    faqs: [
      { q: "Is Sheffield a significant city for OnlyFans creators?", a: "Sheffield has a growing and respected creator community. The city's combination of two major universities, strong creative culture and exceptional affordability produces conditions very favourable for content creation." },
      { q: 'Are there alt or industrial-aesthetic creators in Sheffield?', a: "Yes — Kelham Island's creative community produces creators with a distinctive industrial-cool aesthetic that stands out from mainstream UK content." },
      { q: 'Can I find free Sheffield OnlyFans accounts?', a: "Several Sheffield creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: 'What content types are Sheffield creators known for?', a: "Sheffield creators are particularly strong in authentic amateur content, fitness and outdoor content (benefiting from the Peak District nearby), and alt/alternative niches." },
    ],
    relatedCities: ['leeds', 'manchester', 'nottingham'],
  },
  {
    slug: 'cardiff',
    urlSlug: 'cardiff-onlyfans',
    label: 'Cardiff',
    terms: ['cardiff', 'roath', 'canton cardiff', 'pontcanna', 'bay cardiff'],
    parentRegion: 'wales',
    h1: 'Best OnlyFans Creators in Cardiff',
    metaTitle: 'Best Cardiff OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Cardiff's top OnlyFans creators from Roath, Pontcanna and Cardiff Bay. Browse free and premium Welsh profiles updated daily.",
    intro: "Cardiff has transformed from a Victorian coal capital into one of the UK's most exciting and fastest-growing cities, and its OnlyFans creator community is growing just as rapidly. Wales's capital city benefits from a young, diverse population shaped by three universities and a booming media and TV production sector (BBC Wales is based here). Cardiff creators frequently draw on Welsh identity as content differentiators that resonate strongly with international audiences looking for something genuinely different from the London mainstream.",
    faqs: [
      { q: 'Is Cardiff a growing city for OnlyFans creators?', a: "Yes — Cardiff is one of the UK's fastest-growing creator cities outside England. The combination of university population, media industry presence and a city with rising cultural confidence produces excellent conditions." },
      { q: 'Do Cardiff creators incorporate Welsh identity into their content?', a: "Many do — Welsh language, rugby culture and national pride feature frequently in Cardiff creator bios and content." },
      { q: 'Are there free Cardiff OnlyFans accounts?', a: "Several Cardiff creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: 'What areas of Cardiff have the most creators?', a: "Roath, Canton and Pontcanna have the highest creator density. Cardiff Bay is popular for lifestyle and photogenic location content." },
    ],
    relatedCities: ['swansea', 'bristol', 'birmingham'],
  },
  {
    slug: 'newcastle',
    urlSlug: 'newcastle-onlyfans',
    label: 'Newcastle',
    terms: ['newcastle', 'newcastle upon tyne', 'geordie', 'gateshead', 'jesmond', 'byker'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Newcastle',
    metaTitle: 'Best Newcastle OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: 'Browse OnlyFans creators from Newcastle upon Tyne and the North East. Find local free and premium profiles from Tyneside.',
    intro: "Newcastle upon Tyne brings a raw, infectious energy to the UK OnlyFans creator scene that is entirely its own. The city famous for its legendary nightlife, the iconic Tyne bridges and the warmth of its Geordie community produces creators who embody exactly those qualities: outgoing, fun, direct and genuinely connected to their subscribers. Newcastle's three major universities ensure a constant influx of new student creator talent. Newcastle creators are not trying to be London, and that confidence makes the creator community all the more compelling.",
    faqs: [
      { q: "What is Newcastle's OnlyFans creator scene like?", a: "Newcastle has a vibrant and rapidly growing creator scene that perfectly reflects the city's famous outgoing, warm Geordie character. Creator content tends to be direct, fun and highly fan-engaged." },
      { q: 'Are there student OnlyFans creators in Newcastle?', a: "Yes — Newcastle has three major universities (Newcastle University, Northumbria University, and Newcastle College) that contribute a significant student creator demographic." },
      { q: 'Can I find free Newcastle OnlyFans accounts?', a: "Yes — multiple Newcastle creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: "What content is Newcastle known for?", a: "Newcastle creators produce authentic, personality-driven content that reflects the famous Geordie warmth and directness. Amateur, lifestyle and fitness content are particularly strong." },
    ],
    relatedCities: ['leeds', 'sheffield', 'manchester'],
  },
  {
    slug: 'nottingham',
    urlSlug: 'nottingham-onlyfans',
    label: 'Nottingham',
    terms: ['nottingham', 'lace market', 'hockley nottingham', 'beeston'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Nottingham',
    metaTitle: 'Best Nottingham OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Nottingham's best OnlyFans creators from the Lace Market, Hockley and beyond. Browse free and premium East Midlands profiles.",
    intro: "Nottingham has built one of England's most underappreciated OnlyFans creator communities. Two major universities — the University of Nottingham and Nottingham Trent — provide a combined student population of over 60,000 that forms the backbone of the creator talent pipeline. The Lace Market's revitalised creative and nightlife quarter has attracted artistic and alt creators. Hockley's independent music and vintage scene produces creators with strong alt and goth aesthetics.",
    faqs: [
      { q: "Is Nottingham significant for UK OnlyFans creators?", a: "Nottingham is a growing creator city with a particularly strong student demographic. Two major universities create a constant supply of new talent." },
      { q: 'What content niches are Nottingham creators known for?', a: "Nottingham has strong representation in student/amateur, alt/goth and gaming/cosplay niches. The Lace Market creative scene produces artistically ambitious content." },
      { q: 'Can I find free Nottingham OnlyFans accounts?', a: "Yes — the large student population means Nottingham has a good supply of free-tier creators. Use the Free pricing filter to find them." },
      { q: 'Do Nottingham creators use the city as a backdrop?', a: "Many do — Nottingham Castle, the Lace Market's Victorian architecture and the River Trent provide distinctive backdrop options." },
    ],
    relatedCities: ['birmingham', 'sheffield', 'leicester'],
  },
  {
    slug: 'southampton',
    urlSlug: 'southampton-onlyfans',
    label: 'Southampton',
    terms: ['southampton', 'portswood', 'ocean village', 'shirley southampton'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Southampton',
    metaTitle: 'Best Southampton OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Discover Southampton's OnlyFans creators from Portswood, Ocean Village and across the city. Browse free and premium South Coast profiles.",
    intro: "Southampton occupies a distinctive position in the UK OnlyFans landscape — a major port city with a cosmopolitan character shaped by its maritime heritage, large international student population and proximity to the New Forest and Isle of Wight. The University of Southampton's world-class reputation attracts international students from across the globe, contributing exceptional cultural diversity to the local creator community. Southampton's geographic position on the South Coast makes it a convenient base for creators who work across multiple markets.",
    faqs: [
      { q: 'Does Southampton have a significant OnlyFans creator community?', a: "Southampton has a growing creator community driven primarily by its large and internationally diverse university population." },
      { q: 'Are there free Southampton OnlyFans accounts?', a: "Yes — the student population means Southampton has a healthy supply of free-tier creators. Use the Free pricing filter to find them." },
      { q: "What is Southampton creator content like?", a: "Southampton creators benefit from excellent coastal and countryside access — New Forest, Isle of Wight and South Downs content features regularly." },
      { q: 'Can I find verified creators from Southampton?', a: "Yes — toggle the Verified filter to find identity-confirmed creators from Southampton and the wider Hampshire area." },
    ],
    relatedCities: ['brighton', 'bristol', 'london'],
  },
  {
    slug: 'leicester',
    urlSlug: 'leicester-onlyfans',
    label: 'Leicester',
    terms: ['leicester', 'belgrave leicester', 'knighton', 'braunstone'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Leicester',
    metaTitle: 'Best Leicester OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Leicester's top OnlyFans creators from Belgrave, Knighton and across the East Midlands. Browse free and premium profiles.",
    intro: "Leicester is one of the UK's most genuinely diverse cities — ethnically, culturally and creatively — and this richness flows directly into its OnlyFans creator community. The city's large British Asian communities contribute creator perspectives and aesthetics that are rare in UK creator directories. Two major universities add a strong student demographic. Leicester creators are known for working hard, building genuine fan communities and producing content that prioritises real connection.",
    faqs: [
      { q: 'What makes Leicester creators distinctive?', a: "Leicester's exceptional ethnic and cultural diversity — it's one of the UK's most multicultural cities — produces creator content that represents communities often absent from mainstream UK creator directories." },
      { q: 'Are there South Asian creators based in Leicester?', a: "Yes — Leicester has a large and established British South Asian community that is well-represented in the creator scene." },
      { q: 'Can I find free Leicester OnlyFans accounts?', a: "Yes — the student population and the city's affordability mean Leicester has good availability of free-tier creators. Use the Free pricing filter to find them." },
      { q: 'Does Leicester have a growing creator community?', a: "Leicester's creator community is steadily growing, driven by university growth and the city's increasing cultural confidence." },
    ],
    relatedCities: ['nottingham', 'birmingham', 'sheffield'],
  },
  {
    slug: 'brighton',
    urlSlug: 'brighton-onlyfans',
    label: 'Brighton',
    terms: ['brighton', 'hove', 'brighton hove', 'kemptown', 'north laine'],
    parentRegion: 'england',
    h1: 'Best OnlyFans Creators in Brighton & Hove',
    metaTitle: 'Best Brighton OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Brighton's hottest OnlyFans creators from Kemptown, North Laine and the seafront. Browse free and premium profiles.",
    intro: "Brighton is Britain's most LGBTQ+-affirming city and one of the most creatively exuberant — qualities that translate directly into an OnlyFans creator community that is genuinely extraordinary in its diversity, openness and creative ambition. Kemptown produces some of the UK's most celebrated queer creator content. North Laine's independent, bohemian character attracts alt, goth and artistic creators. Brighton creators are known for radical openness, exceptional personal warmth and content that rarely conforms to any mainstream template.",
    faqs: [
      { q: "Is Brighton known for LGBTQ+ OnlyFans content?", a: "Brighton is arguably the UK's top city for LGBTQ+ creator content. Kemptown and the wider Brighton queer community produce exceptional gay, lesbian, trans and non-binary content that finds global audiences." },
      { q: 'What is the alt/goth creator scene like in Brighton?', a: "Brighton has one of England's strongest alt, goth and alternative creator communities. North Laine's counterculture concentration makes it an ideal base for alternative content." },
      { q: 'Are there free Brighton OnlyFans accounts?', a: "Yes — Brighton has a good supply of free-tier creators reflecting the city's accessible, community-focused ethos. Use the Free pricing filter to find them." },
      { q: "What makes Brighton creator content distinctive?", a: "Brighton content is notable for its openness, diversity and creative ambition. The city's rejection of mainstream conventions means Brighton creators routinely push boundaries." },
    ],
    relatedCities: ['london', 'southampton', 'bristol'],
  },
  {
    slug: 'aberdeen',
    urlSlug: 'aberdeen-onlyfans',
    label: 'Aberdeen',
    terms: ['aberdeen', 'granite city', 'old aberdeen', 'torry', 'westhill'],
    parentRegion: 'scotland',
    h1: 'Best OnlyFans Creators in Aberdeen',
    metaTitle: 'Best Aberdeen OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Discover Aberdeen's OnlyFans creators from the Granite City and beyond. Browse free and premium North East Scotland profiles.",
    intro: "Aberdeen — the Granite City — sits at the gateway to the Scottish Highlands and has quietly developed one of Scotland's most interesting OnlyFans creator communities. The city's oil and gas industry has historically created significant wealth concentration, which translates into a premium subscriber market. Aberdeen's stunning natural surroundings — Royal Deeside, the Aberdeenshire coast and proximity to the Cairngorms National Park — give creators access to some of Britain's most dramatic natural scenery. The University of Aberdeen contributes an educated and internationally diverse student creator demographic.",
    faqs: [
      { q: 'What makes Aberdeen OnlyFans content unique?', a: "Aberdeen's proximity to Royal Deeside, the Aberdeenshire coast and the Cairngorms gives creators access to dramatic Scottish Highland scenery unavailable elsewhere in the UK." },
      { q: 'Is Aberdeen a significant Scottish OnlyFans city?', a: "Aberdeen is Scotland's third city and has a growing creator community. The oil industry wealth concentration supports a premium subscriber base." },
      { q: 'Can I find free Aberdeen OnlyFans accounts?', a: "Several Aberdeen creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: 'Do Aberdeen creators feature Highland scenery?', a: "Many do — Royal Deeside, the coast and the Cairngorms feature frequently in Aberdeen creator content." },
    ],
    relatedCities: ['glasgow', 'edinburgh'],
  },
  {
    slug: 'swansea',
    urlSlug: 'swansea-onlyfans',
    label: 'Swansea',
    terms: ['swansea', 'abertawe', 'gower', 'mumbles', 'uplands swansea'],
    parentRegion: 'wales',
    h1: 'Best OnlyFans Creators in Swansea',
    metaTitle: 'Best Swansea OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Swansea's OnlyFans creators from the Gower Peninsula, Uplands and beyond. Browse free and premium Welsh coastal profiles.",
    intro: "Swansea is the City of Dylan Thomas and the gateway to the Gower Peninsula — one of Britain's finest stretches of coastline — and its OnlyFans creator community reflects the city's unique combination of Welsh cultural pride, coastal beauty and creative ambition. Swansea University's large student population creates perfect conditions for content creation that blends authentic Welsh character with stunning natural backdrops. The Uplands neighbourhood attracts artistic creators whose work has a genuinely distinctive cultural depth.",
    faqs: [
      { q: 'What makes Swansea creators distinctive?', a: "Swansea combines Welsh cultural identity with access to the Gower Peninsula — Britain's first Area of Outstanding Natural Beauty. Creator content from Swansea has both cultural depth and spectacular coastal beauty." },
      { q: 'Do Swansea creators use the Gower as a backdrop?', a: "Many do — the Gower's beaches, cliffs and coastal villages feature frequently in Swansea creator content." },
      { q: 'Are there free Swansea OnlyFans accounts?', a: "Several Swansea creators offer free subscription accounts. Swansea University's student population contributes a good supply of free-tier emerging creators." },
      { q: 'How does Swansea compare to Cardiff for creator volume?', a: "Cardiff is larger and has more creators overall, but Swansea has a distinct character and the Gower backdrop is unique. Both are worth browsing for Welsh creator content." },
    ],
    relatedCities: ['cardiff', 'bristol', 'birmingham'],
  },
  {
    slug: 'belfast',
    urlSlug: 'belfast-onlyfans',
    label: 'Belfast',
    terms: ['belfast', 'northern ireland', 'cathedral quarter', 'botanic belfast', 'titanic quarter'],
    parentRegion: 'northern-ireland',
    h1: 'Best OnlyFans Creators in Belfast',
    metaTitle: 'Best Belfast OnlyFans Creators (2026) | OnlyBritishFans',
    metaDesc: "Find Belfast's top OnlyFans creators from the Cathedral Quarter, Botanic and across Northern Ireland. Browse free and premium profiles.",
    intro: "Belfast has undergone one of Britain's most extraordinary urban transformations. The Cathedral Quarter's creative energy and the Botanic area's student community combine to produce a creator scene that is warm, direct and genuinely community-focused. Belfast creators frequently incorporate Northern Irish identity — the accent, humour, landscape and culture — into their content, creating a personality that fans worldwide find irresistible.",
    faqs: [
      { q: "What is Belfast's OnlyFans creator community like?", a: "Belfast's creator scene reflects the city's extraordinary cultural transformation — warm, direct, creative and deeply community-focused. Creators here build particularly loyal subscriber communities driven by Northern Irish warmth and personality." },
      { q: "Do Belfast creators incorporate Northern Irish culture?", a: "Many do — Northern Irish accent, humour, dialect and cultural references feature prominently in Belfast creator content." },
      { q: 'Are there free Belfast OnlyFans accounts?', a: "Yes — multiple Belfast creators offer free subscription accounts. Use the Free pricing filter to find them." },
      { q: "Do Belfast creators use Northern Ireland's landscapes?", a: "Yes — the Giants Causeway, Causeway Coastal Route, Dark Hedges and Mourne Mountains all feature in content from Belfast-based creators who travel for outdoor shoots." },
    ],
    relatedCities: ['glasgow', 'edinburgh', 'manchester'],
  },
];

export function getCityBySlug(slug: string): CityConfig | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getCityByUrlSlug(urlSlug: string): CityConfig | undefined {
  return cities.find((c) => c.urlSlug === urlSlug);
}

export function getCitiesByRegion(regionSlug: string): CityConfig[] {
  return cities.filter((c) => c.parentRegion === regionSlug);
}